# Title         : tester.yml
# Description   : Configures GitHub Actions to perform integration tests
# Author        : Veltys
# Date          : 2022-12-27
# Version       : 1.3.1
# Usage         : (used externally)
# Notes         : 


name: Testing Action

on: 
  push:
    branches:
      - testing

  pull_request:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: "Test"
        shell: bash
        run: |
          ./grafico_temperaturas.sh -t test.log
